# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit

  - name: posts
    label: Posts
    editor:
      preview: true
    folder: content/posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: date}
      - {label: Subtitle, name: subtitle, widget: text}
      - {label: Content, name: body, widget: markdown}
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
        fields:
          - label: "Category"
            name: "category"
            widget: "relation"
            collection: "postCategories"
            searchFields: ["title"]
            valueField: "title"

  - name: projects
    label: Projects
    editor:
      preview: true
    folder: content/projects
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true 
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Thumbail, name: thumbnail, widget: image, required: false}
      - {label: Type, name: type, widget: select, options: ["standard", "component", "external"]}
      - {label: Component or External URL, name: value, widget: string}
      - {label: Content, name: body, widget: markdown}

  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Settings"
        name: "global-settings"
        fields:
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: Display Photo, name: displayPhoto, widget: image, required: false}
          - label: Social Media Fields
            name: socialMedia
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter URL, name: twitter, widget: string, required: false}
              - {label: LinkedIn URL, name: linkedIn, widget: string, required: false}